### ISSUE TITLE
Domain-restrictions for API-keys

### ISSUE THREAD

**Issue by stianmorsund** [DISCOOS/sar-admin#4]
There are some API-keys needed to communicate with 3rd-party services:

https://github.com/DISCOOS/sar-admin/blob/master/src/app/shared/config.ts

Google Maps API-key supports whitelisting of requests only from specific domains to prevent misuse, so this should be added when the domain of the apps have been decided. Also there should be generated a new API-key for DISCOOS-organization

**Comment by kengu** [comment]
New Google API keys are generated for DISCOOS and HTTP restrictions added by whitelisting https://sar-status*.heruko.com. 

See also #10, #11, #14.
